In [8]:
import pandas as pd
# import datawig

import pandas as pd
import numpy as np

from functions import fill_categorical, fill_numerical
from scipy.stats.contingency import odds_ratio

# Load dataset
data = pd.read_csv('./data/join.csv')

# Initialize list to store imputed columns
cat_cols = [col for col in data.columns if data[col].dtype == 'object']
num_cols = [col for col in data.columns if data[col].dtype != 'object']
cat_data = data[cat_cols]
num_data = data[num_cols]
num_data_p = fill_categorical(cat_data.iloc[:,-6:])
print(num_data_p)

In [2]:
import pandas as pd
# import datawig

import pandas as pd
import numpy as np

from functions import fill_categorical, fill_numerical
from scipy.stats.contingency import odds_ratio

# Load dataset
data = pd.read_csv('./data/join.csv')

# Initialize list to store imputed columns
cat_cols = [col for col in data.columns if data[col].dtype == 'object']
num_cols = [col for col in data.columns if data[col].dtype != 'object']
cat_data = data[cat_cols]
num_data = data[num_cols]

In [7]:
cat_data.iloc[:,-6:]

,rs12628032_NC_000022.11_19980457C>T,rs181362_NC_000022.11_21577779C>T,rs5756931_NC_000022.11_38150026T>C,rs5756932_NC_000022.11_38150111C>T,rs116863293_NC_000022.11_38150112G>A,rs28451064_NC_000021.9_34221526G>A
0,CC,CC,CC,CT,GG,GG
1,CT,CC,TC,CT,GG,GG
2,TT,CC,TT,CC,GG,GG
3,CT,CC,TT,CT,GG,GG
4,CT,CC,TC,TT,GG,GG
...,...,...,...,...,...,...
75,CC,CC,TC,CT,GG,GG
76,CC,TT,TT,CT,GG,GG
77,CT,TT,TC,CC,GG,GG
78,CC,CT,TC,CT,GG,GG
79,CC,CT,TC,CT,GG,GG

In [3]:
cat_data = data[cat_cols]
num_data = data[num_cols]
fill_numerical(num_data.iloc[:,:5])

In [7]:
num_data.iloc[:,:3]

    protocol  год рож  возраст
0         11     1960        62
1         14     1966        56
2         17     1979        43
3         19     1960        62
4         22     1965        57
..       ...      ...       ...
75       156     1962        60
76       157     1963        59
77       160     1977        45
78       161     1963        59
79       163     1958        64

[80 rows x 3 columns]

In [ ]:
fill_numerical(num_data.iloc[:,:5])

In [ ]:
num_data

In [4]:
fill_numerical(num_data)

In [17]:
num_data

,protocol,год рож,возраст,НаследственностьСД,Ож,АГ,ИБС,ПИКС,Рост,Вес,...,сульфанилмочевина,меглитиниды,тиазолиндионы,иДПП-4,арГПП-1,гифлозин,ингибиторы а-глик,инсулинотерапиякороткий,продленный,смешанный
0,11,1960,62,1.0,1.0,0.0,0.0,0.0,160.0,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,NaN
1,14,1966,56,1.0,1.0,1.0,1.0,1.0,152.0,86.0,...,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,36.0,NaN
2,17,1979,43,0.0,1.0,0.0,0.0,0.0,168.0,89.0,...,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN
3,19,1960,62,1.0,1.0,1.0,0.0,0.0,180.0,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,26.0,NaN
4,22,1965,57,0.0,0.0,0.0,0.0,0.0,172.0,91.0,...,60.0,NaN,NaN,NaN,NaN,NaN,NaN,14.0,20.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,156,1962,60,1.0,0.0,0.0,0.0,0.0,174.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0
76,157,1963,59,1.0,0.0,1.0,1.0,0.0,170.0,82.0,...,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,35.0,NaN
77,160,1977,45,1.0,1.0,1.0,1.0,0.0,170.0,95.0,...,60.0,NaN,NaN,NaN,NaN,300.0,NaN,NaN,NaN,NaN
78,161,1963,59,1.0,1.0,1.0,0.0,0.0,168.0,63.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,10.0,NaN
79,163,1958,64,0.0,0.0,0.0,0.0,0.0,165.0,78.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,NaN

In [19]:
cat_data

,name,gender,стаж,инсулинотерапия,ОТ/ОБ,инфарктда,АпоВ/АпоА1,протеинурия.1,СКФ,смешан,...,rs8106813_NC_000019.10_44928401A>G,rs492602_NC_000019.10_48703160A>G,rs575344194_NC_000019.10_48703167C>T,rs681343_NC_000019.10_48703205C>T,rs12628032_NC_000022.11_19980457C>T,rs181362_NC_000022.11_21577779C>T,rs5756931_NC_000022.11_38150026T>C,rs5756932_NC_000022.11_38150111C>T,rs116863293_NC_000022.11_38150112G>A,rs28451064_NC_000021.9_34221526G>A
0,Бектураева М.А.,F,7,1,NaN,0,NaN,следы,82,NaN,...,GG,GG,CC,TT,CC,CC,CC,CT,GG,GG
1,Муратова С.Х.,F,20,10,1.01,ЭКГ,1.11607142857143,0,70,NaN,...,AG,AG,CC,CT,CT,CC,TC,CT,GG,GG
2,Валиев Д.У.,M,14,0,1.01,0,1.1,0,116,50/1000,...,AG,AG,CC,CT,TT,CC,TT,CC,GG,GG
3,Тухтапулатов А.Т.,M,23,23,1.04651162790698,0,0.651851851851852,0,104,NaN,...,AG,AA,CC,CC,CT,CC,TT,CT,GG,GG
4,Сафаров К.Т.,M,9мес,0,1.05494505494506,0,0.76551724137931,0,104,NaN,...,AG,GG,CC,TT,CT,CC,TC,TT,GG,GG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Акбаров К.О.,M,21,10,1.17777777777778,0,0.980263157894737,0.066,89.2,NaN,...,GG,AA,CC,CC,CC,CC,TC,CT,GG,GG
76,Курбанова Д.Х.,F,10,0,1.03260869565217,0,0.810276679841897,0,97.6,100/2000,...,AG,AG,CC,CT,CC,TT,TT,CT,GG,GG
77,Гуломов Д.,M,7,0,1.22222222222222,0,0.598484848484848,следы,92.3,NaN,...,GG,GG,CC,TT,CT,TT,TC,CC,GG,GG
78,Юсупов М.,M,10,0,1.25714285714286,0,0.695652173913043,0,106.9,NaN,...,AG,GG,CC,TT,CC,CT,TC,CT,GG,GG
79,Абдуллаева Т.,F,15,2,1.14893617021277,0,0.832298136645963,0.66,94.9,NaN,...,AG,AG,CC,CT,CC,CT,TC,CT,GG,GG

In [14]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Create sample data with categorical columns
df = pd.DataFrame({'A': ['a', 'b', 'c', 'd', 'e'],
                   'B': ['x', 'y', 'z', 'x', 'y'],
                   'C': ['high', 'low', 'medium', np.none, 'low']})

# Instantiate the OrdinalEncoder and fit-transform the data
encoder = OrdinalEncoder()
df_encoded = pd.DataFrame(encoder.fit_transform(cat_data), columns=cat_data.columns)

# Print the encoded dataframe
print('Encoded dataframe:\n', df_encoded)

# Inverse transform the encoded data to get the original data
df_decoded = pd.DataFrame(encoder.inverse_transform(df_encoded), columns=df.columns)

# Print the decoded dataframe
print('\nDecoded dataframe:\n', df_decoded)

Encoded dataframe:
      A    B    C
0  0.0  0.0  0.0
1  1.0  1.0  1.0
2  2.0  2.0  2.0
3  3.0  0.0  3.0
4  4.0  1.0  1.0

Decoded dataframe:
    A  B       C
0  a  x    high
1  b  y     low
2  c  z  medium
3  d  x    None
4  e  y     low

TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.

In [ ]:

# list of columns for which to calculate odds ratio
genotype_cols = [col for col in data.columns if col != 'case']

In [7]:
data

,protocol,name,gender,год рож,возраст,стаж,инсулинотерапия,НаследственностьСД,Ож,АГ,...,rs8106813_NC_000019.10_44928401A>G,rs492602_NC_000019.10_48703160A>G,rs575344194_NC_000019.10_48703167C>T,rs681343_NC_000019.10_48703205C>T,rs12628032_NC_000022.11_19980457C>T,rs181362_NC_000022.11_21577779C>T,rs5756931_NC_000022.11_38150026T>C,rs5756932_NC_000022.11_38150111C>T,rs116863293_NC_000022.11_38150112G>A,rs28451064_NC_000021.9_34221526G>A
0,11,Бектураева М.А.,F,1960,62,7,1,1.0,1.0,0.0,...,GG,GG,CC,TT,CC,CC,CC,CT,GG,GG
1,14,Муратова С.Х.,F,1966,56,20,10,1.0,1.0,1.0,...,AG,AG,CC,CT,CT,CC,TC,CT,GG,GG
2,17,Валиев Д.У.,M,1979,43,14,0,0.0,1.0,0.0,...,AG,AG,CC,CT,TT,CC,TT,CC,GG,GG
3,19,Тухтапулатов А.Т.,M,1960,62,23,23,1.0,1.0,1.0,...,AG,AA,CC,CC,CT,CC,TT,CT,GG,GG
4,22,Сафаров К.Т.,M,1965,57,9мес,0,0.0,0.0,0.0,...,AG,GG,CC,TT,CT,CC,TC,TT,GG,GG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,156,Акбаров К.О.,M,1962,60,21,10,1.0,0.0,0.0,...,GG,AA,CC,CC,CC,CC,TC,CT,GG,GG
76,157,Курбанова Д.Х.,F,1963,59,10,0,1.0,0.0,1.0,...,AG,AG,CC,CT,CC,TT,TT,CT,GG,GG
77,160,Гуломов Д.,M,1977,45,7,0,1.0,1.0,1.0,...,GG,GG,CC,TT,CT,TT,TC,CC,GG,GG
78,161,Юсупов М.,M,1963,59,10,0,1.0,1.0,1.0,...,AG,GG,CC,TT,CC,CT,TC,CT,GG,GG
79,163,Абдуллаева Т.,F,1958,64,15,2,0.0,0.0,0.0,...,AG,AG,CC,CT,CC,CT,TC,CT,GG,GG

In [ ]:

# loop over genotype columns
for col in genotype_cols:
    # split into case and control groups
    case_group = data[data['case'] == 1][col]
    control_group = data[data['case'] == 0][col]

    # extract wild type and mutant type from column name
    w, m = col[-3:].split('>')
    wild, heterozygous, mutant = w+w, w+m, m+m

    # calculate odds ratio and confidence interval for codominant model
    odds_ratio_codom, lower_ci_codom, upper_ci_codom = odds_ratio(
        np.array([[sum(case_group == wild), sum(case_group == heterozygous), sum(case_group == mutant)],
                  [sum(control_group == wild), sum(control_group == heterozygous), sum(control_group == mutant)]])
    )

    # calculate odds ratio and confidence interval for dominant model
    odds_ratio_dom, lower_ci_dom, upper_ci_dom = odds_ratio(
        np.array([[sum(case_group == heterozygous) + sum(case_group == mutant),
                   sum(case_group == wild)],
                  [sum(control_group == heterozygous) + sum(control_group == mutant),
                   sum(control_group == wild)]])
    )

    # calculate odds ratio and confidence interval for recessive model
    odds_ratio_rec, lower_ci_rec, upper_ci_rec = odds_ratio(
        np.array([[sum(case_group == mutant),
                   sum(case_group == wild) + sum(case_group == heterozygous)],
                  [sum(control_group == mutant),
                   sum(control_group == wild) + sum(control_group == heterozygous)]])
    )

    # print results
    print(f"Odds ratio for {col} (codominant model): {odds_ratio_codom:.2f}, CI [{lower_ci_codom:.2f}, {upper_ci_codom:.2f}]")
    print(f"Odds ratio for {col} (dominant model): {odds_ratio_dom:.2f}, CI [{lower_ci_dom:.2f}, {upper_ci_dom:.2f}]")
    print(f"Odds ratio for {col} (recessive model): {odds_ratio_rec:.2f}, CI [{lower_ci_rec:.2f}, {upper_ci_rec:.2f}]")

In [ ]:

imputed_cols = []

# Loop through each column in DataFrame
for col in df.columns:

    # Skip column if it does not have any missing values
    if df[col].isnull().sum() == 0:
        imputed_cols.append(df[col])
        continue

    # Initialize imputer
    imputer = datawig.SimpleImputer(
        input_columns=list(df.columns),
        output_column=col,
        output_path=f'imputer_model_{col}'
    )

    # Split dataset into training and test sets
    train_df, test_df = datawig.utils.random_split(df)

    # Train imputer
    imputer.fit(train_df)

    # Impute missing values in column
    imputed_col = imputer.predict(test_df)[col]

    # Add imputed column to list
    imputed_cols.append(imputed_col)

# Create new DataFrame with imputed columns
imputed_df = pd.concat(imputed_cols, axis=1)

# Drop any rows that still have missing values
imputed_df = imputed_df.dropna()

In [ ]:


# loop over genotype columns
for col in genotype_cols:
    # split into case and control groups
    case_group = data[data['case'] == 1][col]
    control_group = data[data['case'] == 0][col]

    # extract wild type and mutant type from column name
    w, m = col[-3:].split('>')
    wild, heterozygous, mutant = w+w, w+m, m+m

    # calculate odds ratio and confidence interval for codominant model
    odds_ratio_codom, lower_ci_codom, upper_ci_codom = odds_ratio(
        np.array([[sum(case_group == wild), sum(case_group == heterozygous), sum(case_group == mutant)],
                  [sum(control_group == wild), sum(control_group == heterozygous), sum(control_group == mutant)]])
    )

    # calculate odds ratio and confidence interval for dominant model
    odds_ratio_dom, lower_ci_dom, upper_ci_dom = odds_ratio(
        np.array([[sum(case_group == heterozygous) + sum(case_group == mutant),
                   sum(case_group == wild)],
                  [sum(control_group == heterozygous) + sum(control_group == mutant),
                   sum(control_group == wild)]])
    )

    # calculate odds ratio and confidence interval for recessive model
    odds_ratio_rec, lower_ci_rec, upper_ci_rec = odds_ratio(
        np.array([[sum(case_group == mutant),
                   sum(case_group == wild) + sum(case_group == heterozygous)],
                  [sum(control_group == mutant),
                   sum(control_group == wild) + sum(control_group == heterozygous)]])
    )

    # print results
    print(f"Odds ratio for {col} (codominant model): {odds_ratio_codom:.2f}, CI [{lower_ci_codom:.2f}, {upper_ci_codom:.2f}]")
    print(f"Odds ratio for {col} (dominant model): {odds_ratio_dom:.2f}, CI [{lower_ci_dom:.2f}, {upper_ci_dom:.2f}]")
    print(f"Odds ratio for {col} (recessive model): {odds_ratio_rec:.2f}, CI [{lower_ci_rec:.2f}, {upper_ci_rec:.2f}]")

In [5]:

import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import OneHotEncoder

# Create sample data with missing values
df = pd.DataFrame({'A': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'],
                   'B': ['x', 'y', 'z', None, 'x', 'y', None, 'z', 'y', None, 'x']})

# One-hot encode the categorical variables
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
df_encoded = pd.DataFrame(encoder.fit_transform(df[['A', 'B']]))

# Instantiate the KNN imputer
imputer = KNNImputer(n_neighbors=2)

# Fit and transform the encoded data
df_encoded_filled = pd.DataFrame(imputer.fit_transform(df_encoded))

# Inverse transform the encoded data to get the original categorical variables
df_filled = pd.DataFrame(encoder.inverse_transform(df_encoded_filled))

# Rename the columns of the filled data
df_filled.columns = ['A', 'B']

# Print the original data and the filled data
print('Original data:\n', df)
print('\nFilled data:\n', df_filled)

Original data:
     A     B
0   a     x
1   b     y
2   c     z
3   d  None
4   e     x
5   f     y
6   g  None
7   h     z
8   i     y
9   j  None
10  k     x

Filled data:
     A     B
0   a     x
1   b     y
2   c     z
3   d  None
4   e     x
5   f     y
6   g  None
7   h     z
8   i     y
9   j  None
10  k     x

/home/cat/.local/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(